package com.dodo.project.base.dao.mybatis.model;

import java.util.Date;

public class SystemUser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_user.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_user.username
     *
     * @mbg.generated
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_user.password
     *
     * @mbg.generated
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_user.qq
     *
     * @mbg.generated
     */
    private String qq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_user.email
     *
     * @mbg.generated
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_user.phone
     *
     * @mbg.generated
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_user.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_user.login_num
     *
     * @mbg.generated
     */
    private Long loginNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_user.login_at
     *
     * @mbg.generated
     */
    private Date loginAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_user.status
     *
     * @mbg.generated
     */
    private Short status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_user.system_user_group_id
     *
     * @mbg.generated
     */
    private String systemUserGroupId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_user.is_deleted
     *
     * @mbg.generated
     */
    private Boolean isDeleted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_user.create_by
     *
     * @mbg.generated
     */
    private Long createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_user.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_user.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_user.id
     *
     * @return the value of system_user.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_user.id
     *
     * @param id the value for system_user.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_user.username
     *
     * @return the value of system_user.username
     *
     * @mbg.generated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_user.username
     *
     * @param username the value for system_user.username
     *
     * @mbg.generated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_user.password
     *
     * @return the value of system_user.password
     *
     * @mbg.generated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_user.password
     *
     * @param password the value for system_user.password
     *
     * @mbg.generated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_user.qq
     *
     * @return the value of system_user.qq
     *
     * @mbg.generated
     */
    public String getQq() {
        return qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_user.qq
     *
     * @param qq the value for system_user.qq
     *
     * @mbg.generated
     */
    public void setQq(String qq) {
        this.qq = qq == null ? null : qq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_user.email
     *
     * @return the value of system_user.email
     *
     * @mbg.generated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_user.email
     *
     * @param email the value for system_user.email
     *
     * @mbg.generated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_user.phone
     *
     * @return the value of system_user.phone
     *
     * @mbg.generated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_user.phone
     *
     * @param phone the value for system_user.phone
     *
     * @mbg.generated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_user.remark
     *
     * @return the value of system_user.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_user.remark
     *
     * @param remark the value for system_user.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_user.login_num
     *
     * @return the value of system_user.login_num
     *
     * @mbg.generated
     */
    public Long getLoginNum() {
        return loginNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_user.login_num
     *
     * @param loginNum the value for system_user.login_num
     *
     * @mbg.generated
     */
    public void setLoginNum(Long loginNum) {
        this.loginNum = loginNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_user.login_at
     *
     * @return the value of system_user.login_at
     *
     * @mbg.generated
     */
    public Date getLoginAt() {
        return loginAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_user.login_at
     *
     * @param loginAt the value for system_user.login_at
     *
     * @mbg.generated
     */
    public void setLoginAt(Date loginAt) {
        this.loginAt = loginAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_user.status
     *
     * @return the value of system_user.status
     *
     * @mbg.generated
     */
    public Short getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_user.status
     *
     * @param status the value for system_user.status
     *
     * @mbg.generated
     */
    public void setStatus(Short status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_user.system_user_group_id
     *
     * @return the value of system_user.system_user_group_id
     *
     * @mbg.generated
     */
    public String getSystemUserGroupId() {
        return systemUserGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_user.system_user_group_id
     *
     * @param systemUserGroupId the value for system_user.system_user_group_id
     *
     * @mbg.generated
     */
    public void setSystemUserGroupId(String systemUserGroupId) {
        this.systemUserGroupId = systemUserGroupId == null ? null : systemUserGroupId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_user.is_deleted
     *
     * @return the value of system_user.is_deleted
     *
     * @mbg.generated
     */
    public Boolean getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_user.is_deleted
     *
     * @param isDeleted the value for system_user.is_deleted
     *
     * @mbg.generated
     */
    public void setIsDeleted(Boolean isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_user.create_by
     *
     * @return the value of system_user.create_by
     *
     * @mbg.generated
     */
    public Long getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_user.create_by
     *
     * @param createBy the value for system_user.create_by
     *
     * @mbg.generated
     */
    public void setCreateBy(Long createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_user.create_time
     *
     * @return the value of system_user.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_user.create_time
     *
     * @param createTime the value for system_user.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_user.update_time
     *
     * @return the value of system_user.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_user.update_time
     *
     * @param updateTime the value for system_user.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}