package com.dodo.project.base.dao.mybatis.model;

import java.util.Date;

public class SystemMenuNode {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_menu_node.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_menu_node.menu_id
     *
     * @mbg.generated
     */
    private Integer menuId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_menu_node.is_menu
     *
     * @mbg.generated
     */
    private Boolean isMenu;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_menu_node.is_auth
     *
     * @mbg.generated
     */
    private Boolean isAuth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_menu_node.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_menu_node.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_menu_node.id
     *
     * @return the value of system_menu_node.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_menu_node.id
     *
     * @param id the value for system_menu_node.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_menu_node.menu_id
     *
     * @return the value of system_menu_node.menu_id
     *
     * @mbg.generated
     */
    public Integer getMenuId() {
        return menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_menu_node.menu_id
     *
     * @param menuId the value for system_menu_node.menu_id
     *
     * @mbg.generated
     */
    public void setMenuId(Integer menuId) {
        this.menuId = menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_menu_node.is_menu
     *
     * @return the value of system_menu_node.is_menu
     *
     * @mbg.generated
     */
    public Boolean getIsMenu() {
        return isMenu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_menu_node.is_menu
     *
     * @param isMenu the value for system_menu_node.is_menu
     *
     * @mbg.generated
     */
    public void setIsMenu(Boolean isMenu) {
        this.isMenu = isMenu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_menu_node.is_auth
     *
     * @return the value of system_menu_node.is_auth
     *
     * @mbg.generated
     */
    public Boolean getIsAuth() {
        return isAuth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_menu_node.is_auth
     *
     * @param isAuth the value for system_menu_node.is_auth
     *
     * @mbg.generated
     */
    public void setIsAuth(Boolean isAuth) {
        this.isAuth = isAuth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_menu_node.create_time
     *
     * @return the value of system_menu_node.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_menu_node.create_time
     *
     * @param createTime the value for system_menu_node.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_menu_node.update_time
     *
     * @return the value of system_menu_node.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_menu_node.update_time
     *
     * @param updateTime the value for system_menu_node.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}