package com.dodo.project.base.dao.mybatis.model;

public class SystemRoleMenuMapping {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_role_menu_mapping.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_role_menu_mapping.role_id
     *
     * @mbg.generated
     */
    private Integer roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_role_menu_mapping.menu_id
     *
     * @mbg.generated
     */
    private Integer menuId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_role_menu_mapping.id
     *
     * @return the value of system_role_menu_mapping.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_role_menu_mapping.id
     *
     * @param id the value for system_role_menu_mapping.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_role_menu_mapping.role_id
     *
     * @return the value of system_role_menu_mapping.role_id
     *
     * @mbg.generated
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_role_menu_mapping.role_id
     *
     * @param roleId the value for system_role_menu_mapping.role_id
     *
     * @mbg.generated
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_role_menu_mapping.menu_id
     *
     * @return the value of system_role_menu_mapping.menu_id
     *
     * @mbg.generated
     */
    public Integer getMenuId() {
        return menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_role_menu_mapping.menu_id
     *
     * @param menuId the value for system_role_menu_mapping.menu_id
     *
     * @mbg.generated
     */
    public void setMenuId(Integer menuId) {
        this.menuId = menuId;
    }
}