package com.dodo.project.base.dao.mybatis.model;

import java.util.Date;

public class SystemSubscription {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_subscription.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_subscription.target
     *
     * @mbg.generated
     */
    private Integer target;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_subscription.target_type
     *
     * @mbg.generated
     */
    private String targetType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_subscription.action
     *
     * @mbg.generated
     */
    private String action;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_subscription.system_user_id
     *
     * @mbg.generated
     */
    private Integer systemUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_subscription.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_subscription.id
     *
     * @return the value of system_subscription.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_subscription.id
     *
     * @param id the value for system_subscription.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_subscription.target
     *
     * @return the value of system_subscription.target
     *
     * @mbg.generated
     */
    public Integer getTarget() {
        return target;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_subscription.target
     *
     * @param target the value for system_subscription.target
     *
     * @mbg.generated
     */
    public void setTarget(Integer target) {
        this.target = target;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_subscription.target_type
     *
     * @return the value of system_subscription.target_type
     *
     * @mbg.generated
     */
    public String getTargetType() {
        return targetType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_subscription.target_type
     *
     * @param targetType the value for system_subscription.target_type
     *
     * @mbg.generated
     */
    public void setTargetType(String targetType) {
        this.targetType = targetType == null ? null : targetType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_subscription.action
     *
     * @return the value of system_subscription.action
     *
     * @mbg.generated
     */
    public String getAction() {
        return action;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_subscription.action
     *
     * @param action the value for system_subscription.action
     *
     * @mbg.generated
     */
    public void setAction(String action) {
        this.action = action == null ? null : action.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_subscription.system_user_id
     *
     * @return the value of system_subscription.system_user_id
     *
     * @mbg.generated
     */
    public Integer getSystemUserId() {
        return systemUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_subscription.system_user_id
     *
     * @param systemUserId the value for system_subscription.system_user_id
     *
     * @mbg.generated
     */
    public void setSystemUserId(Integer systemUserId) {
        this.systemUserId = systemUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_subscription.create_time
     *
     * @return the value of system_subscription.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_subscription.create_time
     *
     * @param createTime the value for system_subscription.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}