package com.dodo.project.base.dao.mybatis.model;

import java.util.Date;

public class SystemUserNotify {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_user_notify.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_user_notify.is_read
     *
     * @mbg.generated
     */
    private Boolean isRead;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_user_notify.system_user_id
     *
     * @mbg.generated
     */
    private Integer systemUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_user_notify.notify_id
     *
     * @mbg.generated
     */
    private Integer notifyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_user_notify.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_user_notify.id
     *
     * @return the value of system_user_notify.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_user_notify.id
     *
     * @param id the value for system_user_notify.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_user_notify.is_read
     *
     * @return the value of system_user_notify.is_read
     *
     * @mbg.generated
     */
    public Boolean getIsRead() {
        return isRead;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_user_notify.is_read
     *
     * @param isRead the value for system_user_notify.is_read
     *
     * @mbg.generated
     */
    public void setIsRead(Boolean isRead) {
        this.isRead = isRead;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_user_notify.system_user_id
     *
     * @return the value of system_user_notify.system_user_id
     *
     * @mbg.generated
     */
    public Integer getSystemUserId() {
        return systemUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_user_notify.system_user_id
     *
     * @param systemUserId the value for system_user_notify.system_user_id
     *
     * @mbg.generated
     */
    public void setSystemUserId(Integer systemUserId) {
        this.systemUserId = systemUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_user_notify.notify_id
     *
     * @return the value of system_user_notify.notify_id
     *
     * @mbg.generated
     */
    public Integer getNotifyId() {
        return notifyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_user_notify.notify_id
     *
     * @param notifyId the value for system_user_notify.notify_id
     *
     * @mbg.generated
     */
    public void setNotifyId(Integer notifyId) {
        this.notifyId = notifyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_user_notify.create_time
     *
     * @return the value of system_user_notify.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_user_notify.create_time
     *
     * @param createTime the value for system_user_notify.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}