package com.dodo.project.base.dao.mybatis.model;

import java.util.Date;

public class SystemNotify {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_notify.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_notify.type
     *
     * @mbg.generated
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_notify.target
     *
     * @mbg.generated
     */
    private Integer target;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_notify.target_type
     *
     * @mbg.generated
     */
    private String targetType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_notify.action
     *
     * @mbg.generated
     */
    private String action;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_notify.sender
     *
     * @mbg.generated
     */
    private Integer sender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_notify.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_notify.content
     *
     * @mbg.generated
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_notify.id
     *
     * @return the value of system_notify.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_notify.id
     *
     * @param id the value for system_notify.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_notify.type
     *
     * @return the value of system_notify.type
     *
     * @mbg.generated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_notify.type
     *
     * @param type the value for system_notify.type
     *
     * @mbg.generated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_notify.target
     *
     * @return the value of system_notify.target
     *
     * @mbg.generated
     */
    public Integer getTarget() {
        return target;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_notify.target
     *
     * @param target the value for system_notify.target
     *
     * @mbg.generated
     */
    public void setTarget(Integer target) {
        this.target = target;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_notify.target_type
     *
     * @return the value of system_notify.target_type
     *
     * @mbg.generated
     */
    public String getTargetType() {
        return targetType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_notify.target_type
     *
     * @param targetType the value for system_notify.target_type
     *
     * @mbg.generated
     */
    public void setTargetType(String targetType) {
        this.targetType = targetType == null ? null : targetType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_notify.action
     *
     * @return the value of system_notify.action
     *
     * @mbg.generated
     */
    public String getAction() {
        return action;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_notify.action
     *
     * @param action the value for system_notify.action
     *
     * @mbg.generated
     */
    public void setAction(String action) {
        this.action = action == null ? null : action.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_notify.sender
     *
     * @return the value of system_notify.sender
     *
     * @mbg.generated
     */
    public Integer getSender() {
        return sender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_notify.sender
     *
     * @param sender the value for system_notify.sender
     *
     * @mbg.generated
     */
    public void setSender(Integer sender) {
        this.sender = sender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_notify.create_time
     *
     * @return the value of system_notify.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_notify.create_time
     *
     * @param createTime the value for system_notify.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_notify.content
     *
     * @return the value of system_notify.content
     *
     * @mbg.generated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_notify.content
     *
     * @param content the value for system_notify.content
     *
     * @mbg.generated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}