package com.dodo.project.base.dao.mybatis.model;

public class SystemSubscriptionConfig {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_subscription_config.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_subscription_config.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_subscription_config.action
     *
     * @mbg.generated
     */
    private String action;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_subscription_config.id
     *
     * @return the value of system_subscription_config.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_subscription_config.id
     *
     * @param id the value for system_subscription_config.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_subscription_config.user_id
     *
     * @return the value of system_subscription_config.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_subscription_config.user_id
     *
     * @param userId the value for system_subscription_config.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_subscription_config.action
     *
     * @return the value of system_subscription_config.action
     *
     * @mbg.generated
     */
    public String getAction() {
        return action;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_subscription_config.action
     *
     * @param action the value for system_subscription_config.action
     *
     * @mbg.generated
     */
    public void setAction(String action) {
        this.action = action == null ? null : action.trim();
    }
}