package com.dodo.project.base.dao.mybatis.model;

import java.util.Date;

public class SystemConfig {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_config.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_config.app_name
     *
     * @mbg.generated
     */
    private String appName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_config.app_version
     *
     * @mbg.generated
     */
    private String appVersion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_config.site_name
     *
     * @mbg.generated
     */
    private String siteName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_config.copy_right
     *
     * @mbg.generated
     */
    private String copyRight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_config.browser
     *
     * @mbg.generated
     */
    private String browser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_config.miitbeian
     *
     * @mbg.generated
     */
    private String miitbeian;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_config.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_config.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_config.id
     *
     * @return the value of system_config.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_config.id
     *
     * @param id the value for system_config.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_config.app_name
     *
     * @return the value of system_config.app_name
     *
     * @mbg.generated
     */
    public String getAppName() {
        return appName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_config.app_name
     *
     * @param appName the value for system_config.app_name
     *
     * @mbg.generated
     */
    public void setAppName(String appName) {
        this.appName = appName == null ? null : appName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_config.app_version
     *
     * @return the value of system_config.app_version
     *
     * @mbg.generated
     */
    public String getAppVersion() {
        return appVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_config.app_version
     *
     * @param appVersion the value for system_config.app_version
     *
     * @mbg.generated
     */
    public void setAppVersion(String appVersion) {
        this.appVersion = appVersion == null ? null : appVersion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_config.site_name
     *
     * @return the value of system_config.site_name
     *
     * @mbg.generated
     */
    public String getSiteName() {
        return siteName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_config.site_name
     *
     * @param siteName the value for system_config.site_name
     *
     * @mbg.generated
     */
    public void setSiteName(String siteName) {
        this.siteName = siteName == null ? null : siteName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_config.copy_right
     *
     * @return the value of system_config.copy_right
     *
     * @mbg.generated
     */
    public String getCopyRight() {
        return copyRight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_config.copy_right
     *
     * @param copyRight the value for system_config.copy_right
     *
     * @mbg.generated
     */
    public void setCopyRight(String copyRight) {
        this.copyRight = copyRight == null ? null : copyRight.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_config.browser
     *
     * @return the value of system_config.browser
     *
     * @mbg.generated
     */
    public String getBrowser() {
        return browser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_config.browser
     *
     * @param browser the value for system_config.browser
     *
     * @mbg.generated
     */
    public void setBrowser(String browser) {
        this.browser = browser == null ? null : browser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_config.miitbeian
     *
     * @return the value of system_config.miitbeian
     *
     * @mbg.generated
     */
    public String getMiitbeian() {
        return miitbeian;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_config.miitbeian
     *
     * @param miitbeian the value for system_config.miitbeian
     *
     * @mbg.generated
     */
    public void setMiitbeian(String miitbeian) {
        this.miitbeian = miitbeian == null ? null : miitbeian.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_config.create_time
     *
     * @return the value of system_config.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_config.create_time
     *
     * @param createTime the value for system_config.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_config.update_time
     *
     * @return the value of system_config.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_config.update_time
     *
     * @param updateTime the value for system_config.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}