package com.dodo.project.base.dao.mybatis.model;

import java.util.Date;

public class SystemUserGroupDetail {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_user_group_detail.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_user_group_detail.user_group_id
     *
     * @mbg.generated
     */
    private Integer userGroupId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_user_group_detail.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_user_group_detail.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_user_group_detail.id
     *
     * @return the value of system_user_group_detail.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_user_group_detail.id
     *
     * @param id the value for system_user_group_detail.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_user_group_detail.user_group_id
     *
     * @return the value of system_user_group_detail.user_group_id
     *
     * @mbg.generated
     */
    public Integer getUserGroupId() {
        return userGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_user_group_detail.user_group_id
     *
     * @param userGroupId the value for system_user_group_detail.user_group_id
     *
     * @mbg.generated
     */
    public void setUserGroupId(Integer userGroupId) {
        this.userGroupId = userGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_user_group_detail.user_id
     *
     * @return the value of system_user_group_detail.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_user_group_detail.user_id
     *
     * @param userId the value for system_user_group_detail.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_user_group_detail.create_time
     *
     * @return the value of system_user_group_detail.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_user_group_detail.create_time
     *
     * @param createTime the value for system_user_group_detail.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}