package com.dodo.project.base.dao.mybatis.mapper;

import com.dodo.project.base.dao.mybatis.model.SystemSubscriptionConfig;

public interface SystemSubscriptionConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_subscription_config
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_subscription_config
     *
     * @mbg.generated
     */
    int insert(SystemSubscriptionConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_subscription_config
     *
     * @mbg.generated
     */
    int insertSelective(SystemSubscriptionConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_subscription_config
     *
     * @mbg.generated
     */
    SystemSubscriptionConfig selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_subscription_config
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SystemSubscriptionConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_subscription_config
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SystemSubscriptionConfig record);
}