package com.dodo.project.base.dao.mybatis.mapper;

import com.dodo.project.base.dao.mybatis.model.SystemUserGroupRole;

public interface SystemUserGroupRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_user_group_role
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_user_group_role
     *
     * @mbg.generated
     */
    int insert(SystemUserGroupRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_user_group_role
     *
     * @mbg.generated
     */
    int insertSelective(SystemUserGroupRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_user_group_role
     *
     * @mbg.generated
     */
    SystemUserGroupRole selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_user_group_role
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SystemUserGroupRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_user_group_role
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SystemUserGroupRole record);
}