package com.dodo.project.base.dao.mybatis.mapper;

import com.dodo.project.base.dao.mybatis.bean.SystemUserSearchBean;
import com.dodo.project.base.dao.mybatis.model.SystemUser;
import com.github.pagehelper.Page;

import java.util.List;

public interface SystemUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_user
     *
     * @mbg.generated
     */
    int insert(SystemUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_user
     *
     * @mbg.generated
     */
    int insertSelective(SystemUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_user
     *
     * @mbg.generated
     */
    SystemUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SystemUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SystemUser record);
    
    /* 
    * @Description: 获取数据
    * @Author: walk_code walk_code@163.com
    * @Param: [bean] 
    * @return: java.util.List<com.dodo.project.base.dao.mybatis.model.SystemUser>  
    * @Date: 2019/5/5 19:32
    */ 
    List<SystemUser> getList(SystemUserSearchBean bean);

    /*
    * @Description: 获取列表数据
    * @Author: walk_code walk_code@163.com
    * @Param: [bean]
    * @return: com.github.pagehelper.Page<com.dodo.project.base.dao.mybatis.model.SystemUser>
    * @Date: 2019/5/6 17:03
    */
    Page<SystemUser> getListP(SystemUserSearchBean bean);
}