package com.dodo.project.base.dao.mybatis.mapper;

import com.dodo.project.base.dao.mybatis.model.SystemUserGroup;

public interface SystemUserGroupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_user_group
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_user_group
     *
     * @mbg.generated
     */
    int insert(SystemUserGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_user_group
     *
     * @mbg.generated
     */
    int insertSelective(SystemUserGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_user_group
     *
     * @mbg.generated
     */
    SystemUserGroup selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_user_group
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SystemUserGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_user_group
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SystemUserGroup record);
}