package com.dodo.project.base.dao.mybatis.mapper;

import com.dodo.project.base.dao.mybatis.model.SystemRoleMenuMapping;

public interface SystemRoleMenuMappingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_role_menu_mapping
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_role_menu_mapping
     *
     * @mbg.generated
     */
    int insert(SystemRoleMenuMapping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_role_menu_mapping
     *
     * @mbg.generated
     */
    int insertSelective(SystemRoleMenuMapping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_role_menu_mapping
     *
     * @mbg.generated
     */
    SystemRoleMenuMapping selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_role_menu_mapping
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SystemRoleMenuMapping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_role_menu_mapping
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SystemRoleMenuMapping record);
}