package com.dodo.project.base.dao.mybatis.mapper;

import com.dodo.project.base.dao.mybatis.model.SystemUserNotify;

public interface SystemUserNotifyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_user_notify
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_user_notify
     *
     * @mbg.generated
     */
    int insert(SystemUserNotify record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_user_notify
     *
     * @mbg.generated
     */
    int insertSelective(SystemUserNotify record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_user_notify
     *
     * @mbg.generated
     */
    SystemUserNotify selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_user_notify
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SystemUserNotify record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_user_notify
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SystemUserNotify record);
}