package com.dodo.project.base.dao.mybatis.mapper;

import com.dodo.project.base.dao.mybatis.model.SystemNotify;

public interface SystemNotifyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_notify
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_notify
     *
     * @mbg.generated
     */
    int insert(SystemNotify record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_notify
     *
     * @mbg.generated
     */
    int insertSelective(SystemNotify record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_notify
     *
     * @mbg.generated
     */
    SystemNotify selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_notify
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SystemNotify record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_notify
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(SystemNotify record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_notify
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SystemNotify record);
}