package com.dodo.project.base.dao.mybatis.mapper;

import com.dodo.project.base.dao.mybatis.model.SystemMenuNode;

public interface SystemMenuNodeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_menu_node
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_menu_node
     *
     * @mbg.generated
     */
    int insert(SystemMenuNode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_menu_node
     *
     * @mbg.generated
     */
    int insertSelective(SystemMenuNode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_menu_node
     *
     * @mbg.generated
     */
    SystemMenuNode selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_menu_node
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SystemMenuNode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_menu_node
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SystemMenuNode record);
}